{% set name = "unifunc" %}
{% set version = "1.4.5" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PedroMTQ/UniFunc/archive/refs/tags/{{ version }}.tar.gz
  sha256: cd735aac39e0cc1e5d64cddc7d245ed9bfdc20f4d87cd16a539cd6bcffbac800

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - unifunc=unifunc.__main__:main

requirements:
  host:
    - setuptools >=42
    - wheel
    - pip
    - python {{ python_min }}
  run:
    - nltk >=3.6
    - numpy
    - python >={{ python_min }}
    - requests

test:
  imports:
    - unifunc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PedroMTQ/UniFunc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool for similarity analysis of protein function annotations.
  description: |
    UniFunc is a text mining tool that processes and analysis text similarity
    between a pair of protein function annotations. It is mainly used as a
    cross-linking mechanism or redundancy elimination tool when processing
    annotations without any sort of database identifiers.
  dev_url: https://github.com/PedroMTQ/UniFunc

extra:
  recipe-maintainers:
    - PedroMTQ
